### ISSUE TITLE
icons

### ISSUE THREAD

**Issue by kingkyle** [EvanAgee/vuejs-wordpress-theme-starter#26]
How do i import icons  like font awesome icons for use with this theme?

**Comment by EvanAgee** [comment]
Hey @kingkyle! You have several options:

1. The simplest way is [via their CDN as a <link> tag](https://fontawesome.com/how-to-use/on-the-web/setup/getting-started?using=web-fonts-with-css). 
2. Since this project is already running on webpack, I would install their package via npm and import it into your script. [Instructions can be found here](https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers).

Good luck!
