### ISSUE TITLE
About SEO

### ISSUE THREAD

**Issue by samyfox** [EvanAgee/vuejs-wordpress-theme-starter#27]
Hello,

Can you tell me how my SEO will be affected if I use this starter pack ?

**Comment by minhnhut** [comment]
I think SEO has nothing to do with this starter pack. It is all up to you.

All modern search engine like Google & Microsoft Bing are able to handle javascript content very well nowadays. From my experience of developing SPA with Vue. SEO was a little bit tricky, but as long as you follow search engine's guideline, everything turns out pretty well.

**Comment by giekaton** [comment]
`vue-meta` doesn't work for facebook/twitter, it needs server side rendering or at least pre-rendering.

In the case of this paticular wp-vue repo, I think that you need to provide meta tags with wp, e.g. using Yoast plugin. Then fb will fetch these tags from php.

And for the client side you can use 'vue-meta' plugin, or do it without the plugin like explained here: https://alligator.io/vuejs/vue-router-modify-head/
