### ISSUE TITLE
Handling theme updates when vuejs-wordpress-theme-starter repo updates

### ISSUE THREAD

**Issue by VivekManglani** [EvanAgee/vuejs-wordpress-theme-starter#59]
I've been playing around with the starter theme and had a question regarding best practices when maintaining the theme.

The repo is obviously meant to just be a starter pack and thus we'd need to modify the theme.

If a new version of the starter theme is released how do we merge these changes back into our modified theme?

**Comment by EvanAgee** [comment]
@VivekManglani unfortunately at this time it's a fairly manual process. I know, that sucks. If I were in your shoes I would likely look through the commits to see what was changed and make some of the same changes in your project. Usually the changes I make are fairly small and simple since the nature of this project is to be as make as few assumptions as possible. Thanks!
